<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Force full width content layout
// add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

//Removes Title and Description on Blog Archive
remove_action( 'genesis_before_loop', 'genesis_do_posts_page_heading' );

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd');
	$posts_page = get_option( 'page_for_posts' );
	$post_thumbnail_id = get_post_thumbnail_id( $posts_page );
	$url = wp_get_attachment_image_src( $post_thumbnail_id, 'full_hd' );
	$hero = wp_get_attachment_image_url( get_post_thumbnail_id(get_option('page_for_posts')), 'full' );
    $background_mobile = get_field('background_mobile', get_option('page_for_posts'));
    ?>

    <section class="banner banner-single-post <?php echo (empty($hero)) ? 'empty' : null ?>">

        <div class="banner__rotate bg-cover white" data-mobile="<?php echo $background_mobile ?>"
             style="background-image: url(<?php echo $hero ?>);">

            <?php if (!empty($background_mobile)): ?>
                <style>
                    @media screen and (max-width: 960px) {
                        .banner__rotate {
                            background-image: url(<?php echo $background_mobile ?>) !important;
                        }
                </style>
            <?php endif; ?>

            <div class="banner__content">
				<?php $page_id = get_the_ID();?>
                <h1 class="banner__title"><?php single_post_title(); ?></h1>

                <?php if ($item2 = get_field('position')): ?>
                    <h3><?php echo $item2 ?></h3>
                <?php endif; ?>
                <?php if ($link = get_field('contact_link')): ?>
                    <div class="button__container">
                        <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                           target="<?php if ($link['target']) {
                               echo $link['target'];
                           } else {
                               echo '_parent';
                           } ?>"><?php echo $link['title']; ?></a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </section>
<?php }

genesis();
?>
